Repository Odagada/Trimo-FE, pull requests merged in 2024-02, with the labels that each got.

#24 [Fix] globalcss 배경색 오류 수정
  styles/globals.css
Labels: ⚙️ Fix

#31 [Design] Design system
  .eslintcache
  .github/ISSUE_TEMPLATE/feature.md
  .storybook/main.ts
  .storybook/preview.ts
  apis/axios.ts
  components/atoms/Design.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  public/font/Pretendard-Bold.subset.woff2
  public/font/Pretendard-Medium.subset.woff2
  public/font/Pretendard-Regular.subset.woff2
  public/font/PretendardStd-Bold.woff2
  public/font/PretendardStd-Medium.woff2
  public/font/PretendardStd-Regular.woff2
  public/font/font.css
  stories/assets/Design.stories.tsx
  styles/globals.css
  tailwind.config.ts
Labels: 🖍 Design

#37 [Chore] Eslint rules 추가
  .eslintrc.json
Labels: ⚙️ Chore

#36 Fix/component clickable
  components/atoms/Clickable.tsx
  types/client.types.ts
  utils/getClickableStyle.ts
Labels: ♻️ Refactor

#27 [Feat] Google Map 컴포넌트
  .eslintrc.json
  components/atoms/MapMarker.tsx
  components/atoms/Spinner.tsx
  components/molecules/.gitkeep
  components/molecules/GoogleMapContent.tsx
  components/organisms/.gitkeep
  components/organisms/GoogleMap.tsx
  hooks/useDrawGoogleMap.tsx
  package-lock.json
  package.json
  pages/index.tsx
  tsconfig.json
  utils/markPlaceByQuery.tsx
Labels: 📂 Create, 💡 Feat

#44 Feat/get imoji
  components/atoms/Imoji.tsx
  types/client.types.ts
  utils/getClickableStyle.ts
  utils/getImoji.ts
Labels: 📂 Create, 💡 Feat

#50 [Feat] component image input
  components/atoms/Inputs/ImagesInput.tsx
  components/atoms/icons/DeleteIcon.tsx
  pages/test/index.tsx
  public/images/icons/error-sign.svg
  stories/assets/ImageFiles.stories.ts
  styles/globals.css
  types/client.types.ts
Labels: 📂 Create, 💡 Feat

#53 [Feat] 별점 컴포넌트
  .eslintcache
  components/atoms/Star.tsx
  components/icons/Star.tsx
  components/molecules/StarRate.tsx
  pages/test/index.tsx
  public/images/icons/empty_star.svg
  public/images/icons/filled_star.svg
  public/images/icons/half_star.svg
  stories/assets/StarRate.stories.tsx
  types/client.types.ts
Labels: 📂 Create, 💡 Feat

#55 [Refactor] Google Map Component
  components/atoms/MapMarker.tsx
  components/molecules/GoogleMapContent.tsx
  components/organisms/GoogleMap.tsx
  hooks/useDrawGoogleMap.tsx
  utils/markPlaceByQuery.tsx
Labels: ♻️ Refactor, ❌ Remove, ✏️ Style

#54 [Feat] 드롭다운 컴포넌트
  components/atoms/Dropdowns/HeaderDropdown.tsx
  components/atoms/Dropdowns/OrderDropdown.tsx
  components/atoms/icons/DeleteIcon.tsx
  components/molecules/FilterDropdown.tsx
  components/molecules/NavigationBar.tsx
  public/font/Pretendard-SemiBold.subset.woff2
  public/font/font.css
  public/images/icons/dropdown.svg
  public/images/icons/filter.svg
  stories/assets/Dropdowns.stories.tsx
  stories/assets/FilterDropdown.stories.tsx
  stories/assets/HeaderDropdown.stories.tsx
  stories/assets/ImageFiles.stories.ts
  styles/globals.css
  tailwind.config.ts
  types/client.types.ts
Labels: 📂 Create, 💡 Feat

#59 [Refactor] types 수정
  apis/capsulesQuery.ts
  components/atoms/ImagesCarousel.tsx
  types/client.types.ts
  types/server.types.ts
Labels: ♻️ Refactor, ✏️ Style

#52 [Feat] review card 컴포넌트
  components/atoms/Dropdowns/OrderDropdown.tsx
  components/atoms/ReviewCardTag.tsx
  components/atoms/SingleStarRate.tsx
  components/atoms/Star.tsx
  components/molecules/FilterDropdown.tsx
  components/molecules/ReviewCard.tsx
  stories/assets/ReviewCard.stories.tsx
  stories/assets/SingleStarRate.stories.ts
Labels: 📂 Create, 💡 Feat, ⛔️ 미완성

#61 [Feat] search form
  components/atoms/SearchOption.tsx
  components/atoms/TimePicker.tsx
  components/molecules/SearchFrom.tsx
  components/molecules/TagRadioButton.tsx
  package-lock.json
  package.json
  stories/assets/TimePicker.stories.tsx
Labels: 📂 Create, 💡 Feat

#63 [Refactor] Google Map Multiple Markers
  components/atoms/MapMarker.tsx
  components/molecules/GoogleMapContent.tsx
  components/organisms/GoogleMap.tsx
  hooks/useDrawGoogleMap.tsx
  pages/review/[id].tsx
  types/client.types.ts
Labels: ♻️ Refactor, 🖍 Design, 💡 Feat

#57 [Feat] Review Form
  .eslintcache
  apis/reviewPost.ts
  components/atoms/DatePicker.tsx
  components/atoms/Inputs/ImagesInput.tsx
  components/atoms/ReviewOption.tsx
  components/atoms/Star.tsx
  components/atoms/icons/DeleteIcon.tsx
  components/atoms/useGetForm.tsx
  components/molecules/GoogleAutoComplete.tsx
  components/molecules/ReviewWrite.tsx
  components/molecules/StarRate.tsx
  components/organisms/PlaceForm.tsx
  package-lock.json
  package.json
  pages/review/index.tsx
  stories/assets/ImageFiles.stories.ts
  stories/assets/StarRate.stories.tsx
  types/client.types.ts
  utils/formatDateTime.ts
Labels: 📂 Create, 💡 Feat, ⛔️ 미완성

#65 [Feat] page main 구현
  apis/capsulesQuery.ts
  components/atoms/Dropdowns/OrderDropdown.tsx
  components/atoms/Emoji.tsx
  components/atoms/Footer.tsx
  components/atoms/Inputs/ImagesInput.tsx
  components/atoms/Inputs/SearchBar.tsx
  components/atoms/RateStars.tsx
  components/atoms/SingleStarRate.tsx
  components/atoms/Star.tsx
  components/molecules/FilterDropdown.tsx
  components/molecules/MultiReviewCardSlider.tsx
  components/molecules/NavigationBar.tsx
  components/molecules/PortalSearchBar.tsx
  components/molecules/ReviewCard.tsx
  hooks/.gitkeep
  package-lock.json
  package.json
  pages/index.tsx
  pages/review/[id].tsx
  public/icons/quill.webp
  public/images/DesktopScreenShot1.png
  public/images/DesktopScreenShot2.png
  public/images/desktopMock.png
  public/images/hero-sec.png
  public/images/mobileMock.webp
  stories/assets/ReviewCard.stories.tsx
  stories/assets/SearchBar.stories.tsx
  tailwind.config.ts
  utils/getClickableStyle.ts
Labels: 📂 Create, 💡 Feat, ⚙️ Fix

#62 [Feat]: Signup, Login 페이지 구현, 로그인, 로그아웃 구현
  .eslintcache
  apis/axios.ts
  components/atoms/Clickable.tsx
  components/atoms/Inputs/InputWapper.tsx
  components/atoms/ProgressChip.tsx
  components/atoms/ShadowBox.tsx
  components/molecules/NavigationBar.tsx
  components/molecules/ProgressNavigator.tsx
  constants/signupConstants.tsx
  hooks/signup/useGetUserSocialInfo.tsx
  hooks/signup/useHandleTermsCheck.tsx
  hooks/signup/useRegisterDropdowns.tsx
  hooks/signup/useSignUp.tsx
  hooks/signup/useSubmitAdditionalInfo.tsx
  hooks/signup/useValidateNickname.tsx
  hooks/useManageUserLogin.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/login/index.tsx
  pages/signup/[provider].tsx
  pages/signup/components/SignUpSuccess.tsx
  pages/signup/components/TermsAgreements.tsx
  pages/signup/components/WriteAdditionalInfo.tsx
  pages/signup/index.tsx
  public/images/camera.png
  public/images/icons/blackCheck.svg
  public/images/icons/checked.svg
  public/images/icons/google.png
  public/images/icons/kakao.png
  public/images/icons/naver.png
  public/images/icons/notChecked.svg
  public/logos/logoGroup.png
  public/logos/mainLogo.png
  types/client.types.ts
  utils/getClickableStyle.ts
Labels: ♻️ Refactor, 📂 Create, 💡 Feat

#67 [Refactor] 리뷰 조회 페이지 리팩토링
  components/atoms/RateStars.tsx
  pages/review/[id].tsx
  types/server.types.ts
Labels: ♻️ Refactor

#78 [fix] page/review/[id]에서 try catch 로직 수정
  pages/review/[id].tsx
Labels: ⚙️ Fix

#75 [Refactor] 메인 페이지 리팩토링
  apis/capsulesQuery.ts
  components/atoms/Inputs/SearchBar.tsx
  components/molecules/MultiReviewCardSlider.tsx
  components/organisms/GoogleMap.tsx
  pages/index.tsx
  pages/review/[id].tsx
Labels: ♻️ Refactor, 💡 Feat

#83 [refactor] 리뷰 카드 컴포넌트
  .eslintcache
  components/atoms/MultiStarRate.tsx
  components/molecules/ReviewCard.tsx
  pages/_app.tsx
  pages/review/[id].tsx
  types/server.types.ts
Labels: ♻️ Refactor

#85 [Feat] Toast 구현
  package-lock.json
  package.json
  utils/makeToast.ts
Labels: 📂 Create, 💡 Feat

#84 [refactor] 태그 해제 로직 추가 / 초기화버튼 / Time,Date Picker X버튼 추가
  apis/reviewPost.ts
  components/atoms/DatePicker.tsx
  components/atoms/TimePicker.tsx
  components/molecules/ReviewWrite.tsx
  components/molecules/SearchFrom.tsx
  components/molecules/TagRadioButton.tsx
  hooks/useGetFormField.tsx.ts
  hooks/useGetSearchField.ts
  public/icons/resetIcon.svg
  stories/assets/TimePicker.stories.tsx
  utils/filterObject.ts
  utils/formatDateTime.ts
  utils/formatHours.ts
Labels: ♻️ Refactor, 📂 Create, ⚙️ Fix

#72 [Refactor] SignUp, Login Page, Logout
  .eslintcache
  components/atoms/Dropdowns/HeaderDropdown.tsx
  components/molecules/NavigationBar.tsx
  hooks/signup/useGetUserSocialInfo.tsx
  hooks/signup/useSignUp.tsx
  hooks/signup/useSubmitAdditionalInfo.tsx
  hooks/useGetUserInfo.tsx
  hooks/useManageUserAccessToken.tsx
  hooks/useManageUserLogin.tsx
  pages/404/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/review/index.tsx
  pages/search/index.tsx
  pages/signup/[provider].tsx
  pages/signup/components/SignUpSuccess.tsx
  pages/signup/components/TermsAgreements.tsx
  pages/signup/components/WriteAdditionalInfo.tsx
  stories/assets/NavigationBar.stories.tsx
  types/client.types.ts
  types/server.types.ts
  utils/getAccessTokenFormCookie.ts
  utils/validateByLoginStatus.ts
Labels: ♻️ Refactor, ✍️ Rename

#88 [Fix] calcDate함수 변경
  utils/calcDate.ts
Labels: ⚙️ Fix

#89 chore: aws테스트
  appspec.yml
  deploy.sh
Labels: test

#93 [refactor] format 함수 로직 병합
  components/atoms/DatePicker.tsx
  components/atoms/TimePicker.tsx
  utils/formatHours.ts
  utils/formatTime.ts
Labels: ♻️ Refactor

#96 [refactor] apiKey 연결
  apis/reviewPost.ts
  components/molecules/ReviewWrite.tsx
Labels: ♻️ Refactor

#95 [Refactor] 회원가입 관련 이슈 수정, toast 적용
  .eslintcache
  components/atoms/Dropdowns/HeaderDropdown.tsx
  components/molecules/NavigationBar.tsx
  constants/signupConstants.tsx
  hooks/signup/useGetUserSocialInfo.tsx
  hooks/signup/useHandleTermsCheck.tsx
  hooks/signup/useSignUp.tsx
  hooks/signup/useSubmitAdditionalInfo.tsx
  hooks/signup/useValidateNickname.tsx
  hooks/useManageUserAccessToken.tsx
  pages/_app.tsx
  pages/login/index.tsx
  pages/signup/components/WriteAdditionalInfo.tsx
  utils/makeToast.ts
  utils/validateByLoginStatus.ts
Labels: ♻️ Refactor, 🖍 Design

#86 [Feat] 검색 페이지
  .eslintcache
  apis/capsulesQuery.ts
  components/atoms/Dropdowns/OrderDropdown.tsx
  components/atoms/ReviewCardTag.tsx
  components/atoms/SearchOption.tsx
  components/molecules/FilterDropdown.tsx
  components/molecules/NoResult.tsx
  components/molecules/ReviewCard.tsx
  components/molecules/ReviewList.tsx
  components/molecules/SearchFrom.tsx
  components/organisms/SearchContent.tsx
  hooks/useIntersectionObserver.tsx
  pages/search/index.tsx
  stories/assets/ReviewCard.stories.tsx
  styles/globals.css
  tailwind.config.ts
  types/client.types.ts
  types/server.types.ts
  utils/calcDate.ts
  utils/filterObject.ts
Labels: 📂 Create, 💡 Feat

#81 [Feat] Modal Component
  .eslintcache
  .storybook/preview-body.html
  components/molecules/Modal.tsx
  pages/_document.tsx
  stories/assets/Modal.stories.tsx
Labels: 📂 Create, 💡 Feat

#98 [refactor]: Social Login Redirect Uri 이전
  pages/login/index.tsx
Labels: ♻️ Refactor

#101 Update _document.tsx
  pages/_document.tsx
Labels: ⚙️ Chore

#104 [refactor] Clickable 관련 함수 위치 변경 및 white- 색상 변경
  components/atoms/Clickable.tsx
  pages/index.tsx
  utils/getClickableStyle.ts
Labels: ♻️ Refactor

#99 [feat] meta data
  components/atoms/SearchOption.tsx
  components/molecules/SearchFrom.tsx
  pages/_app.tsx
  public/icons/favicon.png
  public/logos/PreView.png
Labels: 🖍 Design, 💡 Feat

#115 [Design] 404 페이지 반응형 적용 및 eslint 추가 구현
  .eslintcache
  .eslintrc.json
  .husky/pre-commit
  .husky/pre-push
  components/atoms/Clickable.tsx
  components/atoms/DatePicker.tsx
  components/atoms/Design.tsx
  components/atoms/Dropdowns/HeaderDropdown.tsx
  components/atoms/Dropdowns/OrderDropdown.tsx
  components/atoms/Footer.tsx
  components/atoms/ImagesCarousel.tsx
  components/atoms/Inputs/ImagesInput.tsx
  components/atoms/Inputs/Input.tsx
  components/atoms/Inputs/InputWapper.tsx
  components/atoms/Inputs/SearchBar.tsx
  components/atoms/Inputs/TextArea.tsx
  components/atoms/ProgressChip.tsx
  components/atoms/ReviewCardTag.tsx
  components/atoms/ReviewOption.tsx
  components/atoms/SearchOption.tsx
  components/atoms/ShadowBox.tsx
  components/atoms/SingleStarRate.tsx
  components/atoms/Spinner.tsx
  components/atoms/Star.tsx
  components/atoms/TimePicker.tsx
  components/molecules/FilterDropdown.tsx
  components/molecules/GoogleAutoComplete.tsx
  components/molecules/GoogleMapContent.tsx
  components/molecules/Modal.tsx
  components/molecules/MultiReviewCardSlider.tsx
  components/molecules/NavigationBar.tsx
  components/molecules/NoResult.tsx
  components/molecules/ProgressNavigator.tsx
  components/molecules/ReviewCard.tsx
  components/molecules/ReviewList.tsx
  components/molecules/ReviewWrite.tsx
  components/molecules/SearchFrom.tsx
  components/molecules/StarRate.tsx
  components/molecules/TagRadioButton.tsx
  components/organisms/PlaceForm.tsx
  components/organisms/SearchContent.tsx
  package-lock.json
  package.json
  pages/404/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/review/[id].tsx
  pages/search/index.tsx
  pages/signup/[provider].tsx
  pages/signup/components/SignUpSuccess.tsx
  pages/signup/components/TermsAgreements.tsx
  pages/signup/components/WriteAdditionalInfo.tsx
  tailwind.config.ts
Labels: 📂 Create, 🖍 Design

#113 [Refactor] Navbar 반응형 모바일 사이즈 tablet부터로 적용
  components/molecules/NavigationBar.tsx
Labels: ♻️ Refactor

#114 [Refactor] page main 반응형 디자인 적용
  .eslintcache
  .husky/pre-commit
  .husky/pre-push
  components/atoms/DatePicker.tsx
  components/atoms/Footer.tsx
  components/atoms/Inputs/SearchBar.tsx
  components/atoms/ProgressChip.tsx
  components/atoms/ShadowBox.tsx
  components/molecules/MultiReviewCardSlider.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/signup/[provider].tsx
  public/images/mobileMock.webp
  styles/globals.css
  tailwind.config.ts
Labels: 🖍 Design

#117 [Refactor] 회원가입, 로그인 페이지 모바일 반응형 적용
  .eslintcache
  components/atoms/Inputs/InputWapper.tsx
  components/atoms/ProgressChip.tsx
  components/molecules/ProgressNavigator.tsx
  components/molecules/ReviewList.tsx
  components/organisms/SearchContent.tsx
  constants/signupConstants.tsx
  hooks/signup/useHandleTermsCheck.tsx
  pages/login/index.tsx
  pages/signup/[provider].tsx
  pages/signup/components/SignUpSuccess.tsx
  pages/signup/components/TermsAgreements.tsx
  pages/signup/components/WriteAdditionalInfo.tsx
  tailwind.config.ts
Labels: ♻️ Refactor, 🖍 Design

#118 Refactor/review mobile
  .eslintcache
  components/atoms/DatePicker.tsx
  components/atoms/Footer.tsx
  components/atoms/Inputs/ImagesInput.tsx
  components/atoms/Inputs/InputWapper.tsx
  components/atoms/ReviewOption.tsx
  components/molecules/GoogleAutoComplete.tsx
  components/molecules/MultiReviewCardSlider.tsx
  components/molecules/ReviewWrite.tsx
  components/organisms/PlaceForm.tsx
  package.json
  pages/index.tsx
  public/icons/cameraIcon.svg
Labels: 🖍 Design

#124 Refactor/review mobile
  components/atoms/Inputs/ImagesInput.tsx
  components/atoms/ReviewOption.tsx
  components/molecules/ReviewWrite.tsx
Labels: 🖍 Design

#132 [ Refactor ] main 페이지의 카드 scroll을 드래그로 구현
  .eslintcache
  components/molecules/MultiReviewCardSlider.tsx
  components/molecules/ReviewList.tsx
  package-lock.json
  package.json
  pages/index.tsx
  tailwind.config.ts
  utils/makeToast.ts
Labels: ♻️ Refactor, 🖍 Design, 💡 Feat

#136 [Fix] : review scroll hidden
  components/atoms/Inputs/ImagesInput.tsx
Labels: 🖍 Design, ⚙️ Fix

#134 [Feat] MyPage, 정보 수정 페이지 구현, 반응형 적용, 기타 자잘 수정
  .eslintcache
  apis/capsulesQuery.ts
  components/atoms/Dropdowns/HeaderDropdown.tsx
  components/atoms/FilterOptionButtons.tsx
  components/atoms/Inputs/InputWapper.tsx
  components/atoms/icons/DeleteIcon.tsx
  components/molecules/GoogleMapContent.tsx
  components/molecules/NavigationBar.tsx
  components/molecules/TagRadioButton.tsx
  components/organisms/GoogleMap.tsx
  components/organisms/MyReviewGridLayout.tsx
  hooks/signup/useRegisterDropdowns.tsx
  hooks/signup/useSubmitAdditionalInfo.tsx
  hooks/useFilterButtonsPopup.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/mypage/component/UpdateUserInfoForm.tsx
  pages/mypage/edit.tsx
  pages/mypage/index.tsx
  pages/review/[id]/edit.tsx
  pages/review/[id]/index.tsx
  pages/review/index.tsx
  pages/search/index.tsx
  types/client.types.ts
  types/server.types.ts
  utils/formatDateToStr.ts
Labels: ♻️ Refactor, 📂 Create, 🖍 Design, 💡 Feat

#138 fix: footer 개인정보 처리방침 링크
  components/atoms/Footer.tsx
Labels: 📑 Docs, ⚙️ Fix

#139 docs: Readme 초안
  README.md
  etc/검색.gif
  etc/로그인.gif
  etc/리뷰 만들기1.gif
  etc/리뷰 만들기2.gif
  etc/매인.gif
Labels: ⚙️ Chore
